name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-lates
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Android Emulator Runner 
      uses: ReactiveCircus/android-emulator-runner@v2.19.1
      with:
        api-level: 30
        archs: x86-x64
        target: default
        profile: Nexus 6
        run: ./gradlew connectedAndroidTest
